"""edit FK in expense and incoming transaction model. Now use currencies.code, earlier used currencies.id

Revision ID: a86283e1ecd4
Revises: fc0a49df424e
Create Date: 2026-07-18 02:00:21.860959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a86283e1ecd4"
down_revision: Union[str, Sequence[str], None] = "fc0a49df424e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column(
            "currency_type",
            sa.Enum(
                "FIAT",
                "CRYPTO",
                name="currency_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "expense_transactions",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "expense_type",
            sa.Enum(
                "eat",
                "transport",
                "travel",
                "tooth",
                "subscribe",
                "rent",
                "sport",
                "clothes",
                "look",
                "household",
                "cigarettes",
                "alcohol",
                name="expensetype",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(precision=18, scale=2), nullable=False),
        sa.Column("currency_code", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_expense_amount_positive"),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incoming_transactions",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "incoming_type",
            sa.Enum(
                "salary",
                "percentage_of_the_deposit",
                "part_time_job",
                "gift",
                name="incomingtype",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(precision=18, scale=2), nullable=False),
        sa.Column("currency_code", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_income_amount_positive"),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incoming_transactions")
    op.drop_table("expense_transactions")
    op.drop_table("currencies")
    # ### end Alembic commands ###
