"""initial schema

Revision ID: fc0a49df424e
Revises:
Create Date: 2026-07-18 01:54:24.695749

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fc0a49df424e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
